import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:techcity/database-lesson/firebase.dart';

import '../data/notedata.dart';

class NoteEditingScreen extends StatefulWidget {
  final String folderId;
  const NoteEditingScreen({super.key, required this.folderId});

  @override
  State<NoteEditingScreen> createState() => _NoteEditingScreenState();
}

class _NoteEditingScreenState extends State<NoteEditingScreen> {

  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _bodyController = TextEditingController();
  final ImagePicker picker = ImagePicker();
  final FirebaseService _firebaseService = FirebaseService();


  String? _imageUrl;

  Future<void> _uploadImage() async {
    final pickedFile = await picker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      String? downloadUrl = await _firebaseService.uploadImage(pickedFile.path);
      setState(() {
        _imageUrl = downloadUrl;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Add Note')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              controller: _titleController,
              decoration: InputDecoration(labelText: 'Note Title'),
            ),
            TextField(
              controller: _bodyController,
              decoration: InputDecoration(labelText: 'Note Body'),
            ),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                if (_titleController.text.isNotEmpty && _bodyController.text.isNotEmpty) {
                  Note note = Note(
                    id: '', // ID will be generated by Firestore
                    noteTitle: _titleController.text,
                    noteBody: _bodyController.text,
                    noteDate: DateTime.now().toIso8601String(),
                    folderId: widget.folderId,
                  );
                  await _firebaseService.addNote(note);
                  Navigator.pop(context);
                }
              },
              child: Text('Add Note'),
            ),
          ],
        ),
      ),
    );
  }
}


